server:
  port: 8081
spring:
  application:
    name: "CrediYa"
  devtools:
    add-properties: false
  sql:
    init:
      mode: "always"
      schema-locations: "schema.sql"
  profiles:
    include: null
database:
  host: "${LOAN_REQUEST_SERVICE_DB_HOST}"
  port: "${LOAN_REQUEST_SERVICE_DB_PORT}"
  username: "${LOAN_REQUEST_SERVICE_DB_USERNAME}"
  password: "${LOAN_REQUEST_SERVICE_DB_PASSWORD}"
  name: "${LOAN_REQUEST_SERVICE_DB_NAME}"
services:
  user:
    base-url: "http://localhost:8080"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
