name: Build and Push Docker Image - Loan Service

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        if: secrets.DOCKER_USERNAME != ''
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push images
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: crediya/loan-application-service
          IMAGE_TAG: latest
        run: |
          docker build -t crediya-loan-service .

          if [ -n "${{ secrets.DOCKER_USERNAME }}" ]; then
            docker tag crediya-loan-service:latest ${{ secrets.DOCKER_USERNAME }}/crediya-loan-service:$IMAGE_TAG
            docker push ${{ secrets.DOCKER_USERNAME }}/crediya-loan-service:$IMAGE_TAG
          fi

          docker tag crediya-loan-service:latest $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
